package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// genDocsMarker starts every generated page, so scripts/check-lengths.sh
// skips it and so a reader (or a stray manual edit) sees at a glance that
// the file is regenerated, not authored.
const genDocsMarker = "<!-- Code generated by vngcloud gen-docs. DO NOT EDIT. -->"

func newGenDocsCmd(_ *env) *cobra.Command {
	return &cobra.Command{
		Use:    "gen-docs <dir>",
		Hidden: true,
		Args:   exactArgs(1),
		RunE: func(_ *cobra.Command, args []string) error {
			return runGenDocs(args[0])
		},
	}
}

// docService is one service's page content, built once per real operation
// table (billingOps, computeOps, and so on) by buildDocService.
type docService struct {
	name string
	ops  []docOp
}

type docOp struct {
	name       string
	kind       string // "Read", "Write", or "Write, destructive"
	fields     []docField
	queryField string // non-empty for a Get whose Output wraps one resource; see wrappedResourceField
}

// docField is one Input field as gen-docs documents it: a flag (name and
// type) when flags.go can bind it, or a Go field name settable only through
// --cli-input-json otherwise (viaJSON).
type docField struct {
	name     string
	goType   string
	required bool
	viaJSON  bool
}

// buildDocService reflects ops (a concrete []Op[C] for one service) into its
// documentation model. It is generic only so every service's differently
// typed operation table can share this one function.
func buildDocService[C any](name string, ops []Op[C]) docService {
	svc := docService{name: name, ops: make([]docOp, len(ops))}
	for i, op := range ops {
		kind := "Read"
		if op.kind == kindWrite {
			kind = "Write"
			if op.destructive {
				kind = "Write, destructive"
			}
		}
		svc.ops[i] = docOp{
			name:       op.name,
			kind:       kind,
			fields:     docFieldsFor(op.newInput(), op.noFlag),
			queryField: wrappedResourceField(op.methodName, op.newOutput),
		}
	}
	return svc
}

// docFieldsFor lists every exported Input field in declaration order: its
// flag name and Go type when flags.go can bind it and NoFlag (op.go) does
// not mark it (a pointer type is shown with its leading *), or its Go field
// name marked viaJSON otherwise.
func docFieldsFor(inputPtr any, noFlag map[string]bool) []docField {
	t := reflect.TypeOf(inputPtr).Elem()
	fields := make([]docField, 0, t.NumField())
	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		required := f.Tag.Get("vngcloud") == "required"
		if noFlag[f.Name] {
			fields = append(fields, docField{name: f.Name, goType: readableGoType(f.Type), required: required, viaJSON: true})
			continue
		}
		kind, isPointer, ok := supportedFieldKind(f.Type)
		if !ok {
			fields = append(fields, docField{name: f.Name, goType: readableGoType(f.Type), required: required, viaJSON: true})
			continue
		}
		goType := kind.String()
		if isPointer {
			goType = "*" + goType
		}
		fields = append(fields, docField{name: flagNameFor(f.Name), goType: goType, required: required})
	}
	return fields
}

// wrappedResourceField names the Output field a Get command's wiki example
// queries, so a table or text run of that example prints columns instead of
// one compact-JSON cell (the CLI reads design's "Commands": every Get
// response wraps one resource in a single field, such as
// GetServerOutput{Server} or GetQuotaOutput{Quota}). It returns "" for
// anything that is not a Get (a List's Output holds Items, plus page fields
// for a PagedList) or whose Output does not wrap exactly one field, such as
// pricing.GetQuoteOutput, which returns the quote's fields directly rather
// than wrapping one resource.
func wrappedResourceField(methodName string, newOutput func() any) string {
	if !strings.HasPrefix(methodName, "Get") {
		return ""
	}
	t := reflect.TypeOf(newOutput()).Elem()
	if t.Kind() != reflect.Struct {
		return ""
	}
	name, count := "", 0
	for i := range t.NumField() {
		if f := t.Field(i); f.IsExported() {
			count++
			name = f.Name
		}
	}
	if count != 1 {
		return ""
	}
	return name
}

// runGenDocs writes CLI.md and one CLI-<Service>.md per registered service
// into dir, deterministically: no timestamp, no home path, and no
// OS-dependent default appears anywhere in the output, and the only
// map iterated (the shared rename table) is iterated in sorted order. It also
// removes every CLI-*.md file already in dir that this run did not generate,
// so a service renamed or removed from the operation tables does not leave
// its old page behind.
func runGenDocs(dir string) error {
	services := []docService{
		buildDocService("billing", billingOps),
		buildDocService("pricing", pricingOps),
		buildDocService("compute", computeOps),
		buildDocService("network", networkOps),
		buildDocService("dns", dnsOps),
		buildDocService("cdn", cdnOps),
		buildDocService("monitor", monitorOps),
		buildDocService("project", projectOps),
		buildDocService("portal", portalOps),
		buildDocService("loadbalancer", loadbalancerOps),
		buildDocService("volume", volumeOps),
		buildDocService("containerregistry", containerRegistryOps),
		buildDocService("globalloadbalancer", globalLoadBalancerOps),
	}
	sort.Slice(services, func(i, j int) bool { return services[i].name < services[j].name })

	if err := os.MkdirAll(dir, 0o755); err != nil { //nolint:gosec // wiki pages are meant to be world-readable once published
		return err
	}

	generated := map[string]bool{"CLI.md": true}
	for _, svc := range services {
		generated["CLI-"+serviceTitle(svc.name)+".md"] = true
	}
	if err := removeStaleGenDocsFiles(dir, generated); err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(dir, "CLI.md"), []byte(renderCLIPage(services)), 0o644); err != nil { //nolint:gosec // a public documentation page
		return err
	}
	for _, svc := range services {
		path := filepath.Join(dir, "CLI-"+serviceTitle(svc.name)+".md")
		if err := os.WriteFile(path, []byte(renderServicePage(svc)), 0o644); err != nil { //nolint:gosec // a public documentation page
			return err
		}
	}
	return nil
}

// removeStaleGenDocsFiles deletes every CLI-*.md file in dir that keep does
// not name. It only ever deletes a file that starts with genDocsMarker, so a
// hand-authored file that happens to match the CLI-*.md pattern is always
// left alone.
func removeStaleGenDocsFiles(dir string, keep map[string]bool) error {
	entries, err := os.ReadDir(dir)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || keep[name] || !strings.HasPrefix(name, "CLI-") || !strings.HasSuffix(name, ".md") {
			continue
		}
		path := filepath.Join(dir, name)
		data, err := os.ReadFile(path) //nolint:gosec // path is built from a directory entry this same call just listed
		if err != nil {
			return err
		}
		if !strings.HasPrefix(string(data), genDocsMarker) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	return nil
}

// readableGoType renders t's name the way this SDK's own docs write it:
// reflect's "interface {}" becomes the more familiar "any".
func readableGoType(t reflect.Type) string {
	return strings.ReplaceAll(t.String(), "interface {}", "any")
}

// serviceTitle capitalizes a service's command name for its page title and
// file name: "billing" becomes "Billing", but the DNS and CDN initialisms
// stay upper case, and the three compound service names read as separate
// words (the CLI reads design's "Service names and pages"). "project",
// "portal", and "volume" need no case here: the default rule already gives
// them the title they want.
func serviceTitle(name string) string {
	switch name {
	case "dns":
		return "DNS"
	case "cdn":
		return "CDN"
	case "loadbalancer":
		return "LoadBalancer"
	case "globalloadbalancer":
		return "GlobalLoadBalancer"
	case "containerregistry":
		return "ContainerRegistry"
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func renderCLIPage(services []docService) string {
	var b strings.Builder
	b.WriteString(genDocsMarker + "\n\n# CLI\n\n")
	b.WriteString("`vngcloud <service> <operation> [flags]` calls one SDK operation, listed below by " +
		"service. `vngcloud configure` prompts for a profile's region and credentials, `vngcloud configure " +
		"set|get|list` scripts the same, and `vngcloud version` prints the version.\n\n")

	b.WriteString("## Services\n\n")
	for _, svc := range services {
		fmt.Fprintf(&b, "- [%s](CLI-%s.md)\n", serviceTitle(svc.name), serviceTitle(svc.name))
	}
	b.WriteString("\n")

	b.WriteString("## Global flags\n\n")
	b.WriteString("| Flag | Meaning |\n|-|-|\n")
	for _, row := range [][2]string{
		{"--profile", "Profile to use"},
		{"--region", "Region to use"},
		{"--project-id", "Project ID to use"},
		{"--output", "`json`, `table`, or `text`; default from the profile's `output`, else `json`"},
		{"--query", "JMESPath expression to filter output"},
		{"--yes", "Confirm a destructive operation"},
		{"--debug", "Log requests to stderr"},
		{"--read-only", "Refuse every write command"},
	} {
		fmt.Fprintf(&b, "| `%s` | %s |\n", row[0], row[1])
	}
	b.WriteString("\n")

	b.WriteString("## --cli-input-json\n\n")
	b.WriteString("Every operation command also accepts `--cli-input-json '<json>'` or " +
		"`--cli-input-json file://input.json`: a JSON object whose keys are that operation's Input fields, " +
		"matched by their exact, case-sensitive Go name (`ServerID`, never `serverid` or `serverID`). A flag " +
		"given on the same command line is applied after it and wins for that field. Trailing data after the " +
		"JSON value, and a key that names no field, are both usage errors.\n\n")

	b.WriteString("## Exit codes\n\n")
	b.WriteString("| Code | Meaning |\n|-|-|\n")
	for _, row := range [][2]string{
		{"0", "Success"},
		{"1", "API or network error, or a canceled command"},
		{"2", "Usage or config error: bad flags, a missing `--yes`, a read-only refusal, a missing region, " +
			"or an ambiguous project"},
		{"3", "No credentials, a login failure, or a 401 (retried once, except on a toggle write, which is sent only once)"},
		{"4", "Not found"},
	} {
		fmt.Fprintf(&b, "| %s | %s |\n", row[0], row[1])
	}
	b.WriteString("\n")

	b.WriteString("## Error classes\n\n")
	b.WriteString("A failed command prints one JSON line to stderr:\n\n")
	b.WriteString("```json\n{\"error\":{\"code\":\"NotFound\",\"message\":\"server not found\",\"status\":404,\"operation\":\"compute.GetServer\"}}\n```\n\n")
	b.WriteString("`status` and `operation` appear only for an API error, whose `code` is the API's own " +
		"code, or a status-derived fallback code when the API gives none. Every other error names one class: " +
		"`InvalidUsage`, `ReadOnly`, `InvalidConfig`, `NoCredentials`, `LoginFailed`, `RequestFailed`, " +
		"`QueryFailed`, `PageFormat` (a public page, such as the CDN IP range FAQ, no longer matches the " +
		"shape its parser expects; see [CDN](CDN.md)), `UnexpectedStatus` (a vMonitor check has a status " +
		"the SDK does not know, so nothing was sent), `StatusUnconfirmed` (a vMonitor pause or resume " +
		"may have landed but a read did not confirm it; see [Monitor](Monitor.md#pausing-and-resuming)), " +
		"`ZoneBusy` (a vDNS zone stayed busy past the wait before a write, so nothing was sent), " +
		"`WriteFailed` (a vDNS write went to status `ERROR`), `NotSettled` (a vDNS write was accepted " +
		"but did not settle within the wait; do not repeat it), or `NotFound` (a not-found result that " +
		"never became an *APIError, such as monitor.GetChannel's page walk finding no matching ID; a real " +
		"404 already carries code `NotFound` through the API error case above). For `WriteFailed` and " +
		"`NotSettled` the CLI also prints the Output on stdout; see [DNS](DNS.md#waits). `UnexpectedStatus`, " +
		"`StatusUnconfirmed`, `ZoneBusy`, `WriteFailed`, and `NotSettled` all exit 1.\n\n")

	b.WriteString("## Read-only\n\n")
	b.WriteString("Read-only refuses every write command before any request. Any of these turns it on, " +
		"and none can turn it off: `--read-only`; `VNGCLOUD_READ_ONLY` set to `1` or `true`; the profile's " +
		"own `read_only` config key set to `1` or `true` (`read_only = 1` in the config file).\n\n")

	b.WriteString(renderConfigureSection())

	b.WriteString("## Rename table\n\n")
	b.WriteString("A flag or operation name the mechanical kebab-case conversion would otherwise get " +
		"wrong:\n\n")
	b.WriteString("| Name | CLI form |\n|-|-|\n")
	keys := make([]string, 0, len(renameTable))
	for k := range renameTable {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "| `%s` | `%s` |\n", k, renameTable[k])
	}
	return b.String()
}

// renderConfigureSection documents vngcloud configure, built from the same
// configureKeys and configureKeyOrder tables configure.go uses so the page
// can never drift from the actual key set.
func renderConfigureSection() string {
	var b strings.Builder
	b.WriteString("## configure\n\n")
	b.WriteString("`vngcloud configure` prompts for each value below; `configure set <key> <value>`, " +
		"`configure get <key>`, and `configure list` script the same file edits and reads.\n\n")

	b.WriteString("| Key | File |\n|-|-|\n")
	for _, key := range configureKeyOrder {
		_, defaultName := fileFor(key)
		fmt.Fprintf(&b, "| `%s` | %s |\n", key, defaultName)
	}
	b.WriteString("\n")

	b.WriteString("`configure set <key> -` reads the value from stdin instead of argv, so it never appears " +
		"in `ps` output or shell history. `password` and `totp_secret` can only be set this way; a literal " +
		"value for either is refused with exit code 2. `configure get` and `configure list` mask both as " +
		"`****`.\n\n")

	b.WriteString("`configure` and `configure set` refuse to run, with exit code 2, while read-only is on, " +
		"so an agent cannot clear a profile's `read_only` through the CLI; `configure get` and `configure " +
		"list` still work. `configure set read_only` refuses, with exit code 2, to turn `read_only` off for " +
		"a profile that already has it on; clearing it means editing the file by hand.\n\n")

	return b.String()
}

func renderServicePage(svc docService) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n# CLI: %s\n\n", genDocsMarker, serviceTitle(svc.name))

	ops := append([]docOp{}, svc.ops...)
	sort.Slice(ops, func(i, j int) bool { return ops[i].name < ops[j].name })

	for _, op := range ops {
		fmt.Fprintf(&b, "## %s\n\n", op.name)
		fmt.Fprintf(&b, "Kind: %s.\n\n", op.kind)
		if note, ok := docOpNotes[svc.name+" "+op.name]; ok {
			fmt.Fprintf(&b, "%s\n\n", note)
		}
		if len(op.fields) == 0 {
			b.WriteString("No fields.\n\n")
		} else {
			b.WriteString("| Flag | Type | Required |\n|-|-|-|\n")
			for _, f := range op.fields {
				name := "`--" + f.name + "`"
				if f.viaJSON {
					name = "`" + f.name + "` (via `--cli-input-json` only)"
				}
				required := ""
				if f.required {
					required = "yes"
				}
				fmt.Fprintf(&b, "| %s | `%s` | %s |\n", name, f.goType, required)
			}
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "```sh\n%s\n```\n\n", buildExample(svc.name, op))
	}
	return b.String()
}

// monitorChannelRedactionNote documents the CLI's channel redaction rule,
// shared by list-channels and get-channel since both decode the same
// Channel shape through redactChannel before the output ever reaches
// renderOutput.
const monitorChannelRedactionNote = "Redacts every header value and every Address except an Email, SMS, " +
	"or Telegram channel's, since a Webhook, Slack, or other channel's Address can carry a bearer token; " +
	"only Email, SMS, and Telegram addresses print in full."

// monitorCreateChannelAddressNote documents create-channel's literal
// --address guard: the flag table shows --address as a plain, required
// string flag, which would otherwise read as safe to give literally, and an
// inline --cli-input-json value that sets Address or Headers is refused the
// same way even though the flag table cannot show it at all.
const monitorCreateChannelAddressNote = "Refuses a literal --address, or an inline --cli-input-json value that " +
	"sets Address, for every Type except Email, SMS, or Telegram, with exit code 2, since another type's " +
	"address can carry a bearer token. Refuses an inline --cli-input-json value that sets Headers for every " +
	"Type, since Headers has no flag of its own and a Webhook channel's header value can hold a secret. Pass " +
	"Address (and Headers) only through --cli-input-json file://channel.json. The write's own Output is " +
	"redacted the same way a channel read is."

// monitorUpdateChannelAddressNote documents update-channel's literal
// --address guard, which is unconditional: UpdateChannelInput carries no
// Type field, so the CLI cannot tell a Webhook or Slack channel apart from
// an Email, SMS, or Telegram one without a request of its own. An inline
// --cli-input-json value that sets Address or Headers is refused the same
// way, even though the flag table cannot show Headers at all.
const monitorUpdateChannelAddressNote = "Refuses every literal --address, or an inline --cli-input-json value " +
	"that sets Address or Headers, with exit code 2, since this Input carries no Type for the guard to check. " +
	"Pass Address (and Headers) only through --cli-input-json file://channel.json. The write's own Output is " +
	"redacted the same way a channel read is."

// monitorCheckNotificationsNote documents Notifications' own nested shape
// for create-check and update-check: the flag table shows it only as a Go
// type, monitor.CheckNotifications, with no field-level detail, since
// --cli-input-json is the only way to set it at all.
const monitorCheckNotificationsNote = "Notifications' three lists, In-alarm, Up, and Undetermined, name by " +
	"ID which channels a check alerts on each alarm transition; setting Notifications through " +
	"--cli-input-json replaces all three at once, so a partial value, such as only In-alarm, clears the " +
	"other two. Each key is the API's own wire spelling, not the Go field name (In-alarm, never InAlarm); " +
	"an unrecognized key is refused with exit code 2 before any request."

// portalMapRedactionNote documents the CLI's key redaction rule for
// map-backed Outputs, shared by every portal operation (portal.UserInfo,
// Zone, Quota, and TagQuota are all map[string]any) and by containerregistry
// list-repositories (Repository is map[string]any too), so every key the
// API returns reaches this rule.
const portalMapRedactionNote = "Values under a key that looks like a secret " +
	"(password, token, credential, and similar, matched after lower-casing and " +
	"stripping punctuation) print as `<redacted>`, at any depth."

// portalUserInfoNote documents get-user-info's own account-data risk beyond
// the shared map redaction rule: this command prints the caller's own
// account data, which an agent transcript that captures its output keeps
// too.
const portalUserInfoNote = "Prints account data: email, names, user ID, and cash and billing status. " +
	"It is the caller's own account, but an agent transcript that keeps this command's output keeps " +
	"that data too.\n\n" + portalMapRedactionNote

// unverifiedLiveNote builds the shared text for an output shape the live
// checks cannot confirm, because the test account holds no such resource.
// volume and loadbalancer notes reuse it, differing only in the resource
// named.
func unverifiedLiveNote(resource string) string {
	return "Unverified live: the test account has no " + resource +
		", so this output shape comes from GreenNode's official SDK, not a live capture."
}

// volumeShapeUnverifiedNote flags an output shape the live checks cannot
// confirm: the test account holds no volume, so nothing exercises this
// command's decoding against a real response.
var volumeShapeUnverifiedNote = unverifiedLiveNote("volume")

// loadBalancerShapeUnverifiedNote flags an output shape the live checks
// cannot confirm: the test account holds no load balancer, so nothing
// exercises this command's decoding, or any child resource's, against a
// real response.
var loadBalancerShapeUnverifiedNote = unverifiedLiveNote("load balancer")

// certificateShapeUnverifiedNote flags get-certificate's output shape: the
// test account holds no certificate, so nothing exercises its decoding
// against a real response.
var certificateShapeUnverifiedNote = unverifiedLiveNote("certificate")

// containerRegistryRepositoryUnverifiedNote flags list-repositories' output
// shape: the test account holds no repository, so the live call returns an
// empty list and nothing exercises Repository's map-backed decoding against
// a real row.
var containerRegistryRepositoryUnverifiedNote = "Unverified live: the test account has no repository, so the live call returns an empty list. Each row prints the API's own keys unchanged, and those keys have not been seen."

// containerRegistryRepositoryNote combines the unverified-live note above
// with the shared map redaction rule, since containerregistry.Repository is
// map-backed like portal's models.
var containerRegistryRepositoryNote = containerRegistryRepositoryUnverifiedNote + "\n\n" + portalMapRedactionNote

// globalLoadBalancerShapeUnverifiedNote flags an output shape the live
// checks cannot confirm: the test account holds no global load balancer, so
// nothing exercises this command's decoding against a real response.
var globalLoadBalancerShapeUnverifiedNote = unverifiedLiveNote("global load balancer")

// docOpNotes gives one operation a paragraph of prose beyond its kind,
// flags, and example, keyed by "service op-name". An operation goes here
// when its page needs to state a behavior the flag table cannot show, such
// as a redaction rule that changes what an otherwise plain Read command
// prints, or a guard that refuses a flag the table shows as a plain string.
var docOpNotes = map[string]string{
	"monitor list-channels":                   monitorChannelRedactionNote,
	"monitor get-channel":                     monitorChannelRedactionNote,
	"monitor create-channel":                  monitorCreateChannelAddressNote,
	"monitor update-channel":                  monitorUpdateChannelAddressNote,
	"monitor create-check":                    monitorCheckNotificationsNote,
	"monitor update-check":                    monitorCheckNotificationsNote,
	"portal get-user-info":                    portalUserInfoNote,
	"portal list-zones":                       portalMapRedactionNote,
	"portal list-quota-used":                  portalMapRedactionNote,
	"portal get-quota":                        portalMapRedactionNote,
	"portal get-tag-quota":                    portalMapRedactionNote,
	"volume get-volume":                       volumeShapeUnverifiedNote,
	"volume get-underlying-volume":            volumeShapeUnverifiedNote,
	"volume list-snapshots":                   volumeShapeUnverifiedNote,
	"loadbalancer get-load-balancer":          loadBalancerShapeUnverifiedNote,
	"loadbalancer get-certificate":            certificateShapeUnverifiedNote,
	"loadbalancer list-listeners":             loadBalancerShapeUnverifiedNote,
	"loadbalancer get-listener":               loadBalancerShapeUnverifiedNote,
	"loadbalancer list-pools":                 loadBalancerShapeUnverifiedNote,
	"loadbalancer get-pool":                   loadBalancerShapeUnverifiedNote,
	"loadbalancer get-pool-health-monitor":    loadBalancerShapeUnverifiedNote,
	"loadbalancer list-pool-members":          loadBalancerShapeUnverifiedNote,
	"loadbalancer list-policies":              loadBalancerShapeUnverifiedNote,
	"loadbalancer get-policy":                 loadBalancerShapeUnverifiedNote,
	"loadbalancer list-tags":                  loadBalancerShapeUnverifiedNote,
	"containerregistry list-repositories":     containerRegistryRepositoryNote,
	"globalloadbalancer get-load-balancer":    globalLoadBalancerShapeUnverifiedNote,
	"globalloadbalancer list-pools":           globalLoadBalancerShapeUnverifiedNote,
	"globalloadbalancer list-listeners":       globalLoadBalancerShapeUnverifiedNote,
	"globalloadbalancer get-listener":         globalLoadBalancerShapeUnverifiedNote,
	"globalloadbalancer list-pool-members":    globalLoadBalancerShapeUnverifiedNote,
	"globalloadbalancer get-pool-member":      globalLoadBalancerShapeUnverifiedNote,
	"globalloadbalancer list-usage-histories": globalLoadBalancerShapeUnverifiedNote + " The formats and allowed values of --from, --to, and --type are unknown; the CLI passes them through unchecked.",
}

// docJSONPlaceholders gives the JSON literal buildExample writes into
// --cli-input-json for a required Input field that has no flag (viaJSON),
// keyed by its Go field name. A required viaJSON field missing here would
// make buildExample print a command that exits 2 when run as shown, so
// buildExample panics instead of silently omitting the field.
var docJSONPlaceholders = map[string]string{
	"Locations": `["<location-id>"]`,
	"VPCIDs":    `["<vpc-id>"]`,
	"Values":    `[{"Value":"<value>"}]`,
}

// docExampleExtraFlag names one flag buildExample adds to an operation's
// example beyond its required fields, keyed by "service op-name". An
// operation goes here when none of its Input fields are marked "required"
// for this purpose, yet the operation itself rejects a call that leaves a
// whole group of fields unset: update-hosted-zone's only required field is
// HostedZoneID, but UpdateHostedZone also requires at least one of
// Description or VPCIDs, so the plain required-flags-only example would
// print a command that exits 2 with InvalidUsage when run as shown.
// update-record is the same shape: HostedZoneID and RecordID are its only
// required fields, but UpdateRecord also requires at least one other field
// to change. monitor update-check is the same shape again: CheckID is its
// only required field, but UpdateCheck also requires at least one other
// field to change.
var docExampleExtraFlag = map[string]string{
	"dns update-hosted-zone": "description",
	"dns update-record":      "ttl",
	"monitor update-check":   "name",
}

// docExampleOverride gives a full example command line for "service
// op-name", replacing buildExample's generic, per-field derivation.
// create-channel and update-channel need this: buildExample would otherwise
// print a literal --address flag, since Address is a required, flag-settable
// string field, but the CLI's own guard refuses exactly that flag for a real
// Webhook or Slack channel. The override shows the runnable form instead:
// Address (and Headers) through --cli-input-json file://channel.json.
var docExampleOverride = map[string]string{
	"monitor create-channel":           "vngcloud monitor create-channel --name <name> --type Webhook --cli-input-json file://channel.json",
	"monitor update-channel":           "vngcloud monitor update-channel --channel-id <channel-id> --cli-input-json file://channel.json",
	"loadbalancer list-load-balancers": "vngcloud loadbalancer list-load-balancers --query 'Items[].{ID:UUID,Name:Name,Status:DisplayStatus}'",
}

// buildExample builds one example command line for op: docExampleOverride's
// entry for op if any, else every service and operation name, then --<flag>
// <flag> for each required, flag-settable field (a placeholder that names
// the flag, since gen-docs has no sample values), then one --cli-input-json
// holding every required field that has no flag, then the
// docExampleExtraFlag entry for op if any, then --query <field> when op
// wraps one resource (wrappedResourceField), then --yes for a destructive
// write. The example must be runnable as printed, so a required field, or a
// field docExampleExtraFlag names, can never be left out of it.
func buildExample(service string, op docOp) string {
	if override, ok := docExampleOverride[service+" "+op.name]; ok {
		return override
	}
	parts := []string{"vngcloud", service, op.name}
	var jsonPairs []string
	for _, f := range op.fields {
		if !f.required {
			continue
		}
		if !f.viaJSON {
			parts = append(parts, "--"+f.name, "<"+f.name+">")
			continue
		}
		placeholder, ok := docJSONPlaceholders[f.name]
		if !ok {
			panic(fmt.Sprintf("gen-docs: required field %q of %s %s has no --cli-input-json example in docJSONPlaceholders", f.name, service, op.name))
		}
		jsonPairs = append(jsonPairs, fmt.Sprintf("%q:%s", f.name, placeholder))
	}
	if extra, ok := docExampleExtraFlag[service+" "+op.name]; ok {
		parts = append(parts, "--"+extra, "<"+extra+">")
	}
	if len(jsonPairs) > 0 {
		parts = append(parts, "--cli-input-json", "'{"+strings.Join(jsonPairs, ",")+"}'")
	}
	if op.queryField != "" {
		parts = append(parts, "--query", op.queryField)
	}
	if op.kind == "Write, destructive" {
		parts = append(parts, "--yes")
	}
	return strings.Join(parts, " ")
}
