package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// genDocsMarker starts every generated page, so scripts/check-lengths.sh
// skips it and so a reader (or a stray manual edit) sees at a glance that
// the file is regenerated, not authored.
const genDocsMarker = "<!-- Code generated by vngcloud gen-docs. DO NOT EDIT. -->"

func newGenDocsCmd(_ *env) *cobra.Command {
	return &cobra.Command{
		Use:    "gen-docs <dir>",
		Hidden: true,
		Args:   exactArgs(1),
		RunE: func(_ *cobra.Command, args []string) error {
			return runGenDocs(args[0])
		},
	}
}

// docService is one service's page content, built once per real operation
// table (billingOps, computeOps, and so on) by buildDocService.
type docService struct {
	name string
	ops  []docOp
}

type docOp struct {
	name   string
	kind   string // "Read", "Write", or "Write, destructive"
	fields []docField
}

// docField is one Input field as gen-docs documents it: a flag (name and
// type) when flags.go can bind it, or a Go field name settable only through
// --cli-input-json otherwise (viaJSON).
type docField struct {
	name     string
	goType   string
	required bool
	viaJSON  bool
}

// buildDocService reflects ops (a concrete []Op[C] for one service) into its
// documentation model. It is generic only so every service's differently
// typed operation table can share this one function.
func buildDocService[C any](name string, ops []Op[C]) docService {
	svc := docService{name: name, ops: make([]docOp, len(ops))}
	for i, op := range ops {
		kind := "Read"
		if op.kind == kindWrite {
			kind = "Write"
			if op.destructive {
				kind = "Write, destructive"
			}
		}
		svc.ops[i] = docOp{name: op.name, kind: kind, fields: docFieldsFor(op.newInput())}
	}
	return svc
}

// docFieldsFor lists every exported Input field in declaration order: its
// flag name and Go type when flags.go can bind it (a pointer type is shown
// with its leading *), or its Go field name marked viaJSON otherwise.
func docFieldsFor(inputPtr any) []docField {
	t := reflect.TypeOf(inputPtr).Elem()
	fields := make([]docField, 0, t.NumField())
	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		required := f.Tag.Get("vngcloud") == "required"
		kind, isPointer, ok := supportedFieldKind(f.Type)
		if !ok {
			fields = append(fields, docField{name: f.Name, goType: readableGoType(f.Type), required: required, viaJSON: true})
			continue
		}
		goType := kind.String()
		if isPointer {
			goType = "*" + goType
		}
		fields = append(fields, docField{name: flagNameFor(f.Name), goType: goType, required: required})
	}
	return fields
}

// runGenDocs writes CLI.md and one CLI-<Service>.md per registered service
// into dir, deterministically: no timestamp, no home path, and no
// OS-dependent default appears anywhere in the output, and the only
// map iterated (the shared rename table) is iterated in sorted order.
func runGenDocs(dir string) error {
	services := []docService{
		buildDocService("billing", billingOps),
		buildDocService("pricing", pricingOps),
		buildDocService("compute", computeOps),
		buildDocService("network", networkOps),
		buildDocService("dns", dnsOps),
	}
	sort.Slice(services, func(i, j int) bool { return services[i].name < services[j].name })

	if err := os.MkdirAll(dir, 0o755); err != nil { //nolint:gosec // wiki pages are meant to be world-readable once published
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "CLI.md"), []byte(renderCLIPage(services)), 0o644); err != nil { //nolint:gosec // a public documentation page
		return err
	}
	for _, svc := range services {
		path := filepath.Join(dir, "CLI-"+serviceTitle(svc.name)+".md")
		if err := os.WriteFile(path, []byte(renderServicePage(svc)), 0o644); err != nil { //nolint:gosec // a public documentation page
			return err
		}
	}
	return nil
}

// readableGoType renders t's name the way this SDK's own docs write it:
// reflect's "interface {}" becomes the more familiar "any".
func readableGoType(t reflect.Type) string {
	return strings.ReplaceAll(t.String(), "interface {}", "any")
}

// serviceTitle capitalizes a service's command name for its page title and
// file name: "billing" becomes "Billing", but the DNS initialism stays
// upper case.
func serviceTitle(name string) string {
	if name == "dns" {
		return "DNS"
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

func renderCLIPage(services []docService) string {
	var b strings.Builder
	b.WriteString(genDocsMarker + "\n\n# CLI\n\n")
	b.WriteString("`vngcloud <service> <operation> [flags]` calls one SDK operation, listed below by " +
		"service. `vngcloud configure` prompts for a profile's region and credentials, `vngcloud configure " +
		"set|get|list` scripts the same, and `vngcloud version` prints the version.\n\n")

	b.WriteString("## Services\n\n")
	for _, svc := range services {
		fmt.Fprintf(&b, "- [%s](CLI-%s.md)\n", serviceTitle(svc.name), serviceTitle(svc.name))
	}
	b.WriteString("\n")

	b.WriteString("## Global flags\n\n")
	b.WriteString("| Flag | Meaning |\n|-|-|\n")
	for _, row := range [][2]string{
		{"--profile", "Profile to use"},
		{"--region", "Region to use"},
		{"--project-id", "Project ID to use"},
		{"--output", "`json`, `table`, or `text`; default from the profile's `output`, else `json`"},
		{"--query", "JMESPath expression to filter output"},
		{"--yes", "Confirm a destructive operation"},
		{"--debug", "Log requests to stderr"},
		{"--read-only", "Refuse every write command"},
	} {
		fmt.Fprintf(&b, "| `%s` | %s |\n", row[0], row[1])
	}
	b.WriteString("\n")

	b.WriteString("## Exit codes\n\n")
	b.WriteString("| Code | Meaning |\n|-|-|\n")
	for _, row := range [][2]string{
		{"0", "Success"},
		{"1", "API or network error, or a canceled command"},
		{"2", "Usage or config error: bad flags, a missing `--yes`, a read-only refusal, or a missing region"},
		{"3", "No credentials, or a login failure"},
		{"4", "Not found"},
	} {
		fmt.Fprintf(&b, "| %s | %s |\n", row[0], row[1])
	}
	b.WriteString("\n")

	b.WriteString("## Error classes\n\n")
	b.WriteString("A failed command prints one JSON line to stderr:\n\n")
	b.WriteString("```json\n{\"error\":{\"code\":\"NotFound\",\"message\":\"server not found\",\"status\":404,\"operation\":\"compute.GetServer\"}}\n```\n\n")
	b.WriteString("`status` and `operation` appear only for an API error, whose `code` is the API's own " +
		"code. Every other error names one class: `InvalidUsage`, `ReadOnly`, `InvalidConfig`, " +
		"`NoCredentials`, `LoginFailed`, `RequestFailed`, or `QueryFailed`.\n\n")

	b.WriteString("## Read-only\n\n")
	b.WriteString("Read-only refuses every write command before any request. Any of these turns it on, " +
		"and none can turn it off: `--read-only`; `VNGCLOUD_READ_ONLY` set to `1` or `true`; the profile's " +
		"own `read_only` config key set to `true`.\n\n")

	b.WriteString("## Rename table\n\n")
	b.WriteString("A flag or operation name the mechanical kebab-case conversion would otherwise get " +
		"wrong:\n\n")
	b.WriteString("| Name | CLI form |\n|-|-|\n")
	keys := make([]string, 0, len(renameTable))
	for k := range renameTable {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&b, "| `%s` | `%s` |\n", k, renameTable[k])
	}
	return b.String()
}

func renderServicePage(svc docService) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n# CLI: %s\n\n", genDocsMarker, serviceTitle(svc.name))

	ops := append([]docOp{}, svc.ops...)
	sort.Slice(ops, func(i, j int) bool { return ops[i].name < ops[j].name })

	for _, op := range ops {
		fmt.Fprintf(&b, "## %s\n\n", op.name)
		fmt.Fprintf(&b, "Kind: %s.\n\n", op.kind)
		if len(op.fields) == 0 {
			b.WriteString("No fields.\n\n")
		} else {
			b.WriteString("| Flag | Type | Required |\n|-|-|-|\n")
			for _, f := range op.fields {
				name := "`--" + f.name + "`"
				if f.viaJSON {
					name = "`" + f.name + "` (via `--cli-input-json` only)"
				}
				required := ""
				if f.required {
					required = "yes"
				}
				fmt.Fprintf(&b, "| %s | `%s` | %s |\n", name, f.goType, required)
			}
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "```sh\n%s\n```\n\n", buildExample(svc.name, op))
	}
	return b.String()
}

// buildExample builds one example command line for op: every service and
// operation name, then --<flag> <flag> for each required, flag-settable
// field (a placeholder that names the flag, since gen-docs has no sample
// values), then --yes for a destructive write.
func buildExample(service string, op docOp) string {
	parts := []string{"vngcloud", service, op.name}
	for _, f := range op.fields {
		if !f.required || f.viaJSON {
			continue
		}
		parts = append(parts, "--"+f.name, "<"+f.name+">")
	}
	if op.kind == "Write, destructive" {
		parts = append(parts, "--yes")
	}
	return strings.Join(parts, " ")
}
